name: 'Elastic Cloud Control (ecctl) tool installer'
description: 'Install a specific version of ecctl tool and cache it.'
author: 'Yoichi Kawasaki @yokawasa'
inputs: 
  version:
    description: 'Version of ecctl'
    required: true
    default: 'latest'
outputs:
  ecctl-path:
    description: 'Path to the cached ecctl tool'
branding:
  icon: 'terminal'
  color: 'blue'
runs:
  using: 'node12'
  main: 'dist/index.js'
