name: 'Elastic Cloud Control (ecctl) tool installer'
description: 'Install a specific version of ecctl tool and cache it.'
inputs: 
  version:
    description: 'Version of ecctl'
    required: true
    default: 'latest'
outputs:
  ecctl-path:
    description: 'Path to the cached ecctl tool'
branding:
  color: 'blue'
runs:
  using: 'node12'
  main: 'lib/main.js'

